# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire_HT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_TVA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_TTC', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('type_produit', models.CharField(max_length=50)),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_unite', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('montant_total_HT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_total_TVA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_total_TTC', models.DecimalField(decimal_places=2, max_digits=15)),
                ('etat', models.CharField(max_length=50)),
                ('provenance_fonds', models.CharField(max_length=20)),
                ('type_achat', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
    ]
