# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '0001_initial'),
        ('achats', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.fournisseur'),
        ),
        migrations.AddField(
            model_name='achatproduit',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='achats.achat'),
        ),
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise'),
        ),
        migrations.AddField(
            model_name='achatproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.unitemesure'),
        ),
    ]
