# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=50, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
    ]
