# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '0001_initial'),
        ('achats', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_immobilisation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('date_acquisition', models.DateField()),
                ('valeur_achat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amortissement_cumule', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valeur_nette', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(max_length=50)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.achat')),
                ('attribue_a_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
    ]
