# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email_admin', models.EmailField(max_length=254)),
                ('pays', models.CharField(blank=True, max_length=50)),
                ('abonnement_debut', models.DateField()),
                ('abonnement_fin', models.DateField()),
                ('statut_abonnement', models.CharField(default='actif', max_length=20)),
                ('blocage_total', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_offre', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_utilisateurs', models.IntegerField()),
                ('restrictions', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.offre')),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.offre'),
        ),
    ]
