# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '0001_initial'),
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_banque', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_caisse', models.CharField(max_length=100)),
                ('type_caisse', models.CharField(max_length=50)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField()),
                ('compte_comptable', models.CharField(max_length=50)),
                ('type_ecriture', models.CharField(choices=[('Débit', 'Débit'), ('Crédit', 'Crédit')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('dette', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='InventaireStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateField()),
                ('quantite_theorique', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantite_physique', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ecart', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorisation_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorisation_totale', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commentaire', models.TextField(blank=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.produit')),
            ],
        ),
        migrations.CreateModel(
            name='OperationBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_operation', models.DateField()),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.banque')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='OperationCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_operation', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.caisse')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
    ]
