# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupement', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=1)),
                ('localite', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('carte_id', models.CharField(max_length=50)),
                ('part_sociale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotisation_annuelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_paiement', models.CharField(max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonnement.entreprise')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membre.membre')),
            ],
        ),
    ]
